name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  algoliasearch: ^1.41.0
  appwrite: ^12.0.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_web_auth_2: ^3.1.2
  font_awesome_flutter: ^10.12.0
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  intl: ^0.20.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
